# Generated by Django 3.2.25 on 2024-03-10 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='name',
            new_name='merchant_name',
        ),
        migrations.RenameField(
            model_name='shopcategory',
            old_name='name',
            new_name='category_name',
        ),
    ]
